Do not try to set ptyxis profile if dconf and gsettings are not installed

diff --git a/ublue/distrobox/distrobox_update_containers b/ublue/distrobox/distrobox_update_containers
--- a/ublue/distrobox/distrobox_update_containers
+++ b/ublue/distrobox/distrobox_update_containers
@@ -112,6 +112,12 @@ pull_and_recreate_container() {
 }
 
 set_ptyxis_profile() {
+  for cmd in dconf gsettings; do
+    if ! command -v "$cmd"; then
+      log "* $cmd not installed. Cannot set ptyxis profile"
+      return 0
+    fi
+  done
   # update the container id in the profile
   container_id="$(podman inspect "$CONTAINER" --format '{{.ID}}')"
   # update terminal profile
